//--- Automatically generated header file: Do Not Edit Manually! ---
//
// Generated from N:\UrbanChaos\sounds.slb on 16/11/99 14:09:12
//

#ifndef _sound_id_h_
#define _sound_id_h_

extern CBYTE *sound_list[];

enum Waves {
    S_NULL,
    S_WIND_START,
    S_WIND_END                                         = S_WIND_START + 6,
    S_THUNDER_START,
    S_THUNDER_END                                      = S_THUNDER_START + 3,
    S_RAIN_START,
    S_AMBIENCE_START,
    S_AMBIENCE_END,
    S_SIREN_START,
    S_SIREN_END                                        = S_SIREN_START + 3,
    S_PISTOL_DRY,
    S_PISTOL_SHOT,
    S_PISTOL_SHOT_END,
    S_RICOCHET_START,
    S_RICOCHET_END                                     = S_RICOCHET_START + 5,
    S_FEMALE_DIE_1,
    S_FEMALE_DIE_2,
    S_MALE_DIE_1,
    S_MALE_DIE_2,
    S_PUNCH_START,
    S_PUNCH_END                                        = S_PUNCH_START + 4,
    S_NECK_BREAK,
    S_FOOTS_WOOD_START,
    S_FOOTS_WOOD_END                                   = S_FOOTS_WOOD_START + 3,
    S_FOOTS_CAR_START,
    S_FOOTS_CAR_END                                    = S_FOOTS_CAR_START + 3,
    S_FOOTS_GRASS_START,
    S_FOOTS_GRASS_END                                  = S_FOOTS_GRASS_START + 3,
    S_FOOTS_GRAVEL_START,
    S_FOOTS_GRAVEL_END                                 = S_FOOTS_GRAVEL_START + 3,
    S_FOOTS_ROAD_START,
    S_FOOTS_ROAD_END                                   = S_FOOTS_ROAD_START + 3,
    S_FOOTS_RUNG_START,
    S_FOOTS_RUNG_END                                   = S_FOOTS_RUNG_START + 3,
    S_FOOTS_PUDDLE_START,
    S_FOOTS_PUDDLE_END                                 = S_FOOTS_PUDDLE_START + 3,
    S_FOOTS_SEWER_START,
    S_FOOTS_SEWER_END                                  = S_FOOTS_SEWER_START + 3,
    S_CLIMB_SEWER,
    S_ELEC_START,
    S_ELEC_END                                         = S_ELEC_START + 4,
    S_KICK_CAN,
    S_CAR_START,
    S_CAR_IDLE,
    S_CAR_ACC1,
    S_CAR_ACC2,
    S_CAR_ACC3,
    S_CAR_STOP,
    S_VAN_START,
    S_VAN_IDLE,
    S_VAN_STOP,
    S_RAT_START,
    S_RAT_END                                          = S_RAT_START + 4,
    S_DOG_START,
    S_DOG_END                                          = S_DOG_START + 2,
    S_CAT_START,
    S_CAT_END                                          = S_CAT_START + 3,
    S_MANHOLE_COVER,
    S_SWITCH,
    S_FIRE,
    S_EXPLODE_START,
    S_EXPLODE_END                                      = S_EXPLODE_START + 2,
    S_EXPLODE_AMBIENT,
    S_FIREBALL,
    S_EXPLODE_SMALL,
    S_EXPLODE_MEDIUM,
    S_EXPLODE_BIG,
    S_HELI,
    S_HEY_YOU,
    S_THUMP_SQUISH,
    S_WATERFALL,
    S_BEEP,
    S_GETOUTTHEWAY,
    S_KNIFE_START,
    S_KNIFE_END                                        = S_KNIFE_START + 3,
    S_SHOTGUN_LOAD,
    S_SHOTGUN_PUMP,
    S_SHOTGUN_SHOT,
    S_MENU_START,
    S_MENU_END                                         = S_MENU_START + 5,
    S_SKID_START,
    S_SKID_END                                         = S_SKID_START + 2,
    S_SKID_SLOW_START,
    S_SKID_SLOW_END,
    S_CAR_SMASH_START,
    S_CAR_SMASH_END                                    = S_CAR_SMASH_START + 3,
    S_CAR_BUMP,
    S_CARX_START,
    S_CARX_CRUISE,
    S_CARX_OLD_END,
    S_CARX_DECEL,
    S_CARX_IDLE,
    S_CARX_END,
    S_CAR_SUSPENSION_START,
    S_CAR_SUSPENSION_END                               = S_CAR_SUSPENSION_START + 3,
    S_CAR_HORN_START,
    S_CAR_HORN_END                                     = S_CAR_HORN_START + 2,
    S_CAR_SCRAPE_START,
    S_CAR_SCRAPE_END                                   = S_CAR_SCRAPE_START + 3,
    S_TRAFFIC_CONE,
    S_CROW,
    S_ZIPWIRE,
    S_DARCI_ARREST,
    S_DARCI_DEAD_START,
    S_DARCI_DEAD_END                                   = S_DARCI_DEAD_START + 2,
    S_DARCI_DYING,
    S_DARCI_EFFORT_START,
    S_DARCI_EFFORT_END                                 = S_DARCI_EFFORT_START + 2,
    S_DARCI_SHORT_EFFORT,
    S_DARCI_HIT_START,
    S_DARCI_HIT_END                                    = S_DARCI_HIT_START + 4,
    S_DARCI_SCREAM_FALL_START,
    S_DARCI_SCREAM_FALL_END,
    S_DARCI_SCREAM_NO_START,
    S_DARCI_SCREAM_NO_END,
    S_DARCI_OUTOFBREATH,
    S_DARCI_LOOKOUT_START,
    S_DARCI_LOOKOUT_END,
    S_DARCI_HEY_START,
    S_DARCI_HEY_END,
    S_DARCI_HI_START,
    S_DARCI_HI_END,
    S_DARCI_SEEYA,
    S_DARCI_FREEZE_START,
    S_DARCI_FREEZE_END,
    S_DARCI_STOP_POLICE,
    S_ROPER_HIT_START,
    S_ROPER_HIT_END                                    = S_ROPER_HIT_START + 6,
    S_ROPER_EFFORT_START,
    S_ROPER_EFFORT_END                                 = S_ROPER_EFFORT_START + 3,
    S_ROPER_SHORT_EFFORT,
    S_ROPER_SCREAM_FALL_START,
    S_ROPER_SCREAM_FALL_END                            = S_ROPER_SCREAM_FALL_START + 2,
    S_ROPER_ARREST,
    S_ROPER_OUTOFBREATH,
    S_ROPER_HEY,
    S_ROPER_DARCI_START,
    S_ROPER_DARCI_END                                  = S_ROPER_DARCI_START + 2,
    S_ROPER_NICE_DAY,
    S_HEART_FAIL,
    S_BTHUG_UNCERTAIN_START,
    S_BTHUG_UNCERTAIN_END                              = S_BTHUG_UNCERTAIN_START + 6,
    S_BTHUG_ALERT_START,
    S_BTHUG_ALERT_END                                  = S_BTHUG_ALERT_START + 5,
    S_WTHUG1_UNCERTAIN_START,
    S_WTHUG1_UNCERTAIN_END                             = S_WTHUG1_UNCERTAIN_START + 8,
    S_WTHUG1_ALERT_START,
    S_WTHUG1_ALERT_END                                 = S_WTHUG1_ALERT_START + 5,
    S_WTHUG2_UNCERTAIN_START,
    S_WTHUG2_UNCERTAIN_END                             = S_WTHUG2_UNCERTAIN_START + 7,
    S_WTHUG2_ALERT_START,
    S_WTHUG2_ALERT_END                                 = S_WTHUG2_ALERT_START + 5,
    S_MUSIC_START,
    S_TUNE_SEWER,
    S_TUNE_CHAOS,
    S_TUNE_CLUB,
    S_TUNE_DANGER_GREEN,
    S_TUNE_DANGER_YELLOW,
    S_TUNE_DANGER_RED,
    S_TUNE_FIGHT,
    S_TUNE_FIGHT2,
    S_TUNE_SPRINT,
    S_TUNE_SPRINT2,
    S_TUNE_CRAWL,
    S_TUNE_DRIVING_START,
    S_TUNE_DRIVING,
    S_TUNE_DRIVING2,
    S_TUNE_TIMER1,
    S_MUSIC_END,
    S_TEST_MUSIC_START,
    S_TEST_MUSIC_END                                   = S_TEST_MUSIC_START + 2,
    S_CAR_SIREN1,
    S_DOG1,
    S_DOG2,
    S_DOG3,
    S_DOG4,
    S_FIRE_CRACKLE,
    S_FIRE_HYDRANT,
    S_GLASS_STEP1,
    S_GLASS_STEP2,
    S_GLASS_STEP3,
    S_GLASS_STEP4,
    S_GLASS_LAND1,
    S_GRASS_STEP1,
    S_GRASS_STEP2,
    S_GRASS_STEP3,
    S_GRASS_STEP4,
    S_GRASS_LAND1,
    S_METAL_LAND_HEAVY,
    S_METAL_LAND_LITE,
    S_STREET_LAND1,
    S_WATER_LAND1,
    S_WATER_OUT,
    S_WET_LAND1,
    S_WOOD_LAND1,
    S_SNOW_STEP1,
    S_SNOW_STEP2,
    S_SNOW_STEP3,
    S_SNOW_STEP4,
    S_SNOW_LAND1,
    S_BIRD_START,
    S_BIRD_END                                         = S_BIRD_START + 6,
    S_START_SNOW_WIND,
    S_END_SNOW_WIND                                    = S_START_SNOW_WIND + 4,
    S_AMB_WOLF1,
    S_AMB_AIRCRAFT1,
    S_BARREL_BREAK,
    S_BARREL_START,
    S_BARREL_END                                       = S_BARREL_START + 2,
    S_CONE,
    S_GLASS_START,
    S_GLASS_END                                        = S_GLASS_START + 4,
    S_HIDDENITEM,
    S_SEARCH_END,
    S_SLIDE_START,
    S_SLIDE_END,
    S_TRASHCAN_END,
    S_BIRDCALL,
    S_COCKATOO_START,
    S_COCKATOO_END,
    S_CRICKET,
    S_FOGHORN,
    S_TROPICAL,
    S_ACIEEED,
    S_DEAD,
    S_ROPERIN,
    S_CUTSCENE_STING,
    S_CITYMISC_START,
    S_CITYMISC_END                                     = S_CITYMISC_START + 2,
    S_RADIO_MESSAGE,
    S_STAB_MISS,
    S_STAB_START,
    S_STAB_END                                         = S_STAB_START + 2,
    S_BAT_HIT,
    S_BAT_MALE_START,
    S_BAT_MALE_END,
    S_BAT_FEMALE_START,
    S_BAT_FEMALE_END,
    S_BRIEFING,
    S_LEVEL_COMPLETE,
    S_TUNE_FRONTEND,
    S_CAR_DOOR,
    S_ITEM_REVEALED,
    S_BAT_SQUEEK_START,
    S_BAT_SQUEEK_END                                   = S_BAT_SQUEEK_START + 5,
    S_BALROG_GROWL_START,
    S_BALROG_GROWL_END                                 = S_BALROG_GROWL_START + 2,
    S_BALROG_STEP_START,
    S_BALROG_STEP_END,
    S_BALROG_DEATH,
    S_BALROG_ROAR,
    S_BALROG_FIREBALL,
    S_SHOTGUN_RELOAD_START,
    S_SHOTGUN_RELOAD_END,
    S_MENU_CLICK_START,
    S_MENU_CLICK_END,
    S_AK47_BURST,
    S_AK47_SHOT,
    S_PICKUP_SWISH,
    S_CAR_REVERSE_START,
    S_CAR_REVERSE_LOOP,
    S_CAR_REVERSE_END,
    S_KICK_IN_THE_NUTS_START,
    S_KICK_IN_THE_NUTS_END,
    S_AMB_WOLF2,
    S_AMB_WOLF3,
    S_AMB_POLICE1,
    S_AMB_POSHEETA,
    S_AMB_OFFICE1,
    S_TUNE_COMBAT_TRAINING,
    S_TUNE_DRIVING_TRAINING,
    S_TUNE_CLUB_START,
    S_TUNE_CLUB_END,
    S_TUNE_ASSAULT_TRAINING,
    S_JUDO_CHOP,
    S_MIB_EXPLODE,
    S_MIB_LEVITATE,
    S_HARD_FOOTSTEP_START,
    S_HARD_FOOTSTEP_END                                = S_HARD_FOOTSTEP_START + 3,
    S_ROPER_DEADSAFE_TAUNT_START,
    S_ROPER_DEADSAFE_TAUNT_END                         = S_ROPER_DEADSAFE_TAUNT_START + 5,
    S_ROPER_FIGHT_TAUNT_START,
    S_ROPER_FIGHT_TAUNT_END                            = S_ROPER_FIGHT_TAUNT_START + 9,
    S_ROPER_SHOOT_START,
    S_ROPER_SHOOT_END                                  = S_ROPER_SHOOT_START + 3,
    S_DARCI_MISC_TAUNT_START,
    S_DARCI_MISC_TAUNT_END                             = S_DARCI_MISC_TAUNT_START + 6,
    S_DARCI_FIGHT_TAUNT_START,
    S_DARCI_FIGHT_TAUNT_END                            = S_DARCI_FIGHT_TAUNT_START + 12,
    S_DARCI_SHOOT_TAUNT_START,
    S_DARCI_SHOOT_TAUNT_END                            = S_DARCI_SHOOT_TAUNT_START + 3,
    S_DARCI_DEADSAFE_TAUNT_START,
    S_DARCI_DEADSAFE_TAUNT_END                         = S_DARCI_DEADSAFE_TAUNT_START + 5,
    S_DARCI_ARREST_START,
    S_DARCI_ARREST_END                                 = S_DARCI_ARREST_START + 3,
    S_RASTA_TAUNT_START,
    S_RASTA_TAUNT_END                                  = S_RASTA_TAUNT_START + 8,
    S_GGREY_TAUNT_START,
    S_GGREY_TAUNT_END                                  = S_GGREY_TAUNT_START + 9,
    S_GRED_TAUNT_START,
    S_GRED_TAUNT_END                                   = S_GRED_TAUNT_START + 4,
    S_GRED2_TAUNT_START,
    S_GRED2_TAUNT_END                                  = S_GRED2_TAUNT_START + 4,
    S_COP_ARREST_START,
    S_COP_ARREST_END                                   = S_COP_ARREST_START + 3,
    S_COP_DIE_START,
    S_COP_DIE_END                                      = S_COP_DIE_START + 4,
    S_COP_PAIN_START,
    S_COP_PAIN_END                                     = S_COP_PAIN_START + 4,
    S_COP_TAUNT_START,
    S_COP_TAUNT_END                                    = S_COP_TAUNT_START + 7,
    S_RECKONING_LOOP,
    S_TUNE_BONUS,
    S_MIB_GUN,
    S_MIB_GUN_WDOWN,
    S_SOFT_STEP_START,
    S_SOFT_STEP_END                                    = S_SOFT_STEP_START + 3,
    S_MIB_WARNING,
    S_PAINTGUN,
    S_SCREAM_FEMALE_START,
    S_SCREAM_FEMALE_END,
    S_SCREAM_MALE,
    S_CREDITS_LOOP,
    S_BIG_BANG_START,
    S_BIG_BANG_END,
    S_RASTA_PAIN_START,
    S_RASTA_PAIN_END                                   = S_RASTA_PAIN_START + 3,
    S_GRED_PAIN_START,
    S_GRED_PAIN_END                                    = S_GRED_PAIN_START + 3,
    S_HOSTAGE_PAIN_START,
    S_HOSTAGE_PAIN_END                                 = S_HOSTAGE_PAIN_START + 3,
    S_WORKMAN_PAIN_START,
    S_WORKMAN_PAIN_END                                 = S_WORKMAN_PAIN_START + 3,
    S_GGREY_PAIN_START,
    S_GGREY_PAIN_END                                   = S_GGREY_PAIN_START + 2,
    S_TRAMP_PAIN_START,
    S_TRAMP_PAIN_END                                   = S_TRAMP_PAIN_START + 4,
    S_TUNE_ASIAN_DUB,
	S_FRONT_END_LOOP_EDIT
};

#endif
