//--- Automatically generated header file: Do Not Edit Manually! ---
//
// Generated from N:\UrbanChaos\sounds.slb on 16/11/99 14:09:12
//

#include "MFStdLib.h"

#ifndef PSX
CBYTE *sound_list[] = {
    "NULL.wav",
    "f_WIND1.wav",
    "f_WIND3.wav",
    "f_WIND4.wav",
    "f_WIND5.wav",
    "f_WINDsecond2.wav",
    "f_WINDsecond6.wav",
    "f_WINDsecond7.wav",
    "f_THNDR1.wav",
    "f_THNDR2.wav",
    "f_LGTNG1.wav",
    "f_LGTNG2.wav",
    "f_RAIN.wav",
    " *DL* f_WETAMB.wav",
    "f_CTYAMB.wav",
    "f_siren1.wav",
    "f_siren2.wav",
    "f_siren3.wav",
    "amb_car1.wav",
    "f_pDUD.wav",
    "f_pSHOT1.wav",
    "f_pSHOT2.wav",
    "f_RICO1.wav",
    "f_RICO2.wav",
    "f_RICO3.wav",
    "f_RICO4.wav",
    "f_RICO5.wav",
    "f_RICO6.wav",
    "f_fDIE1.wav",
    "f_fDIE2.wav",
    "f_mDIE1.wav",
    "f_mDIE2.wav",
    "f_PUNCH1.wav",
    "f_PUNCH2.wav",
    "f_PUNCH3.wav",
    "f_PUNCH4.wav",
    "f_PUNCH5.wav",
    "f_NCKBRK.wav",
    "f_ftBOX1.wav",
    "f_ftBOX2.wav",
    "f_ftBOX3.wav",
    "f_ftBOX4.wav",
    "f_ftCAR1.wav",
    "f_ftCAR2.wav",
    "f_ftCAR3.wav",
    "f_ftCAR4.wav",
    "f_ftGRS1.wav",
    "f_ftGRS2.wav",
    "f_ftGRS3.wav",
    "f_ftGRS4.wav",
    "f_ftGVL1.wav",
    "f_ftGVL2.wav",
    "f_ftGVL3.wav",
    "f_ftGVL4.wav",
    "f_ftHRD1.wav",
    "f_ftHRD2.wav",
    "f_ftHRD3.wav",
    "f_ftHRD4.wav",
    "f_ftSTL1.wav",
    "f_ftSTL2.wav",
    "f_ftSTL3.wav",
    "f_ftSTL4.wav",
    "f_ftwet1.wav",
    "f_ftwet2.wav",
    "f_ftwet3.wav",
    "f_ftwet4.wav",
    "f_ftSWR1.wav",
    "f_ftSWR2.wav",
    "f_ftSWR3.wav",
    "f_ftSWR4.wav",
    "clmSWR1.wav",
    "f_ELEC1.wav",
    "f_ELEC2.wav",
    "f_ELEC3.wav",
    "f_ELEC4.wav",
    "f_ELEC5.wav",
    "f_CanKIK.wav",
    "car_strt.wav",
    "car_idle.wav",
    " *DL* f_cACC1.wav",
    " *DL* f_cACC2.wav",
    " *DL* f_cACC3.wav",
    " *DL* car_stop.wav",
    "van_strt.wav",
    "van_idle.wav",
    " *DL* van_stop.wav",
    " *DL* f_RAT1.wav",
    " *DL* f_RAT2.wav",
    " *DL* f_RAT3.wav",
    " *DL* f_RAT4.wav",
    " *DL* f_RAT5.wav",
    "f_DOG1.wav",
    "f_DOG2.wav",
    "f_DOG3.wav",
    "f_CAT1.wav",
    "f_CAT2.wav",
    "f_CAT3.wav",
    "f_CAT4.wav",
    "*NOTUSED*f_MANHOL.wav",
    "f_SWITCH.wav",
    "f_FIRE.wav",
    "f_EXPLD1.wav",
    "f_EXPLD2.wav",
    "f_EXPLD3.wav",
    "amb_expl.wav",
    "ExploFireBall1.wav",
    "ExploMed1.wav",
    "ExploLrg1.wav",
    "ExploMetal1.wav",
    "heli.wav",
    "whoryou.wav",
    "thumpsquish.wav",
    "*NOTUSED*hevywatr.wav",
    "beep.wav",
    " *DL* getouttheway.wav",
    "f_knSWP1.wav",
    "f_knSWP2.wav",
    "f_knSWP3.wav",
    "f_knSWP4.wav",
    "f_sLOAD.wav",
    "f_sPUMP.wav",
    "f_sSHOT1.wav",
    "f_MENU09.wav",
    "f_MENU10.wav",
    "f_MENU11.wav",
    "f_MENU04.wav",
    "f_MENU13.wav",
    "f_MENU14.wav",
    "Skid1.wav",
    "Skid2.wav",
    "Skid3.wav",
    "SlowSkidx1.wav",
    "SlowSkidx2.wav",
    "Impact1.wav",
    "Impact2.wav",
    "Impact3.wav",
    "MedCrash2.wav",
    "ImpactSml.wav",
    " *DL* CarXPullAway.wav",
    "CarXLoop.wav",
    " *DL* CarXDecel.wav",
    "CarXDecel2.wav",
    "CarXIdle.wav",
    "CarXEnd.wav",
    "Suspension1.wav",
    "Suspension2.wav",
    "Suspension3.wav",
    "Suspension4.wav",
    "Horn1.wav",
    "Horn2.wav",
    "Horn3.wav",
    "Scrape3.wav",
    "Scrape5.wav",
    "Scrape6.wav",
    "Scrape4.wav",
    "Cone1.wav",
    "crow3.wav",
    "ZipWire.wav",
    "darci\\under arrest.WAV",
    "darci\\die 1.WAV",
    "darci\\die 2.WAV",
    "darci\\die 3.WAV",
    "darci\\death breath.WAV",
    "darci\\effort 1.WAV",
    "darci\\effort 2.WAV",
    "darci\\effort 3.WAV",
    "darci\\short effort.wav",
    "darci\\hit 1.WAV",
    "darci\\hit 2.WAV",
    "darci\\hit 3.WAV",
    "darci\\hit 4.WAV",
    "darci\\hit 5.WAV",
    "darci\\scream fall 2.WAV",
    "darci\\scream fall.WAV",
    "darci\\no scream 2.WAV",
    "darci\\no scream.WAV",
    "darci\\running breath.WAV",
    "darci\\lookout warning.WAV",
    "darci\\lookout aggr.WAV",
    "darci\\hey.WAV",
    "darci\\hey 2.WAV",
    "darci\\hi.WAV",
    "darci\\hi 2.WAV",
    "darci\\see ya 2.WAV",
    "darci\\freeze.wav",
    "darci\\freeze tk2.wav",
    "darci\\stop police tk2.wav",
    "roper\\hit1.WAV",
    "roper\\hit2.WAV",
    "roper\\hit3.WAV",
    "roper\\hit4.WAV",
    "roper\\hit5.WAV",
    "roper\\hit6.WAV",
    "roper\\hit7.WAV",
    "roper\\effort1.WAV",
    "roper\\effort2.WAV",
    "roper\\effort3.WAV",
    "roper\\effort4.WAV",
    "roper\\short effort.wav",
    "roper\\roper fall1.WAV",
    "roper\\roper fall2.WAV",
    "roper\\roper fall3.WAV",
    "roper\\you're busted tk2.WAV",
    "roper\\run breath.WAV",
    "roper\\heyhello.WAV",
    "roper\\darci ack.WAV",
    "roper\\darci question.WAV",
    "roper\\darci overhere.WAV",
    "roper\\have nice day2.WAV",
    "borrowed\\heartfail.wav",
    "bthug1\\huh 1.wav",
    "bthug1\\huh 2.wav",
    "bthug1\\whats that.wav",
    "bthug1\\whats that 2.wav",
    "bthug1\\did you hear.wav",
    "bthug1\\whos there.wav",
    "bthug1\\whos there 2.wav",
    "bthug1\\hey you.wav",
    "bthug1\\hey you 2.wav",
    "bthug1\\there they are.wav",
    "bthug1\\there they are 2.wav",
    "bthug1\\over there.wav",
    "bthug1\\over there 2.wav",
    "wthug1\\huh.wav",
    "wthug1\\huh 2.wav",
    "wthug1\\huh 3.wav",
    "wthug1\\what was that.wav",
    "wthug1\\what was that 2.wav",
    "wthug1\\did you hear that.wav",
    "wthug1\\did you hear that 2.wav",
    "wthug1\\whos there.wav",
    "wthug1\\whos there 2.wav",
    "wthug1\\hey you.wav",
    "wthug1\\hey you 2.wav",
    "wthug1\\over there.wav",
    "wthug1\\over there 2.wav",
    "wthug1\\there they are.wav",
    "wthug1\\there they are 2.wav",
    "wthug2\\huh 1.wav",
    "wthug2\\huh 2.wav",
    "wthug2\\what was that.wav",
    "wthug2\\what was that2.wav",
    "wthug2\\you hear that.wav",
    "wthug2\\you hear that 2.wav",
    "wthug2\\whos there.wav",
    "wthug2\\whos there 2.wav",
    "wthug2\\hey you.wav",
    "wthug2\\hey you 2.wav",
    "wthug2\\over there.wav",
    "wthug2\\over there 2.wav",
    "wthug2\\there they are.wav",
    "wthug2\\there they are 2.wav",
    " *DL* music01\\Sneak.wav",
    " *DL* music01\\Sewer.wav",
    " *DL* GeneralMusic\\ChaosTheEndMONO.wav",
    " *DL* GeneralMusic\\Club1.wav",
    "Sfx\\DangerGreen.wav",
    " *DL* Sfx\\DangerYellow.wav",
    "Sfx\\DangerRed.wav",
    " *DL* music01\\darci\\Fight1MONO.wav",
    " *DL* music01\\darci\\Fight2MONO.wav",
    " *DL* music01\\darci\\Sprint1MONO.wav",
    " *DL* music01\\darci\\Sprint2MONO.wav",
    " *DL* music01\\darci\\CrawlMONO.wav",
    " *DL* music01\\darci\\DrivingStart.wav",
    " *DL* music01\\darci\\Driving1MONO.wav",
    " *DL* music01\\darci\\Driving2MONO.wav",
    " *DL* GeneralMusic\\Timer122MONO.wav",
    " *DL* music01\\Panic.wav",
    " *DL* music01\\Music1.wav",
    " *DL* music01\\Music2.wav",
    " *DL* music01\\Music3.wav",
    "General\\CopSiren1.wav",
    " *DL* General\\AttackDog.wav",
    " *DL* General\\Angdog.wav",
    " *DL* General\\Dog.wav",
    " *DL* General\\Dog2.wav",
    " *DL* General\\FireCrackle1.wav",
    "General\\FireHydrant.wav",
    " *DL* Footsteps\\GlassStep1.wav",
    " *DL* Footsteps\\GlassStep2.wav",
    " *DL* Footsteps\\GlassStep3.wav",
    " *DL* Footsteps\\GlassStep4.wav",
    " *DL* Footsteps\\GlassLand1.wav",
    " *DL* Footsteps\\GrassyStep1.wav",
    " *DL* Footsteps\\GrassyStep2.wav",
    " *DL* Footsteps\\GrassyStep3.wav",
    " *DL* Footsteps\\GrassyStep4.wav",
    " *DL* Footsteps\\GravelLand1.wav",
    " *DL* Footsteps\\MetalLandHeavy1.wav",
    " *DL* Footsteps\\MetalLandLite1.wav",
    " *DL* Footsteps\\StreetLand1.wav",
    " *DL* Footsteps\\WaterLand1.wav",
    " *DL* Footsteps\\WaterOut1.wav",
    " *DL* Footsteps\\WetLand1.wav",
    " *DL* Footsteps\\WoodLand1.wav",
    " *DL* Footsteps\\SnowStep1.wav",
    " *DL* Footsteps\\SnowStep2.wav",
    " *DL* Footsteps\\SnowStep3.wav",
    " *DL* Footsteps\\SnowStep4.wav",
    " *DL* Footsteps\\SnowLand1.wav",
    " *DL* Ambience\\BirdSong1.wav",
    "Ambience\\BirdSong2Shortenough.wav",
    " *DL* Ambience\\BirdSong3.wav",
    " *DL* Ambience\\BirdSong4.wav",
    " *DL* Ambience\\BirdSong5.wav",
    "Ambience\\BirdSong6Shortenough.wav",
    " *DL* Ambience\\Peacock1.wav",
    " *DL* Ambience\\SnowWind1.wav",
    " *DL* Ambience\\SnowWind5.wav",
    " *DL* Ambience\\SnowWind2.wav",
    " *DL* Ambience\\SnowWind3.wav",
    " *DL* Ambience\\SnowWind4.wav",
    " *DL* Ambience\\Wolfhowl.wav",
    " *DL* Ambience\\Aircraft1.wav",
    "sfx080799+\\Barrel1.wav",
    "sfx080799+\\Barrel2.wav",
    "sfx080799+\\Barrel3.wav",
    "sfx080799+\\Barrel4.wav",
    "sfx080799+\\Cone1.wav",
    " *DL* sfx080799+\\Glass1.wav",
    " *DL* sfx080799+\\Glass2.wav",
    " *DL* sfx080799+\\Glass3.wav",
    " *DL* sfx080799+\\Glass4.wav",
    " *DL* sfx080799+\\Glass5.wav",
    "sfx080799+\\HiddenItemRev2.wav",
    "sfx080799+\\Search2.wav",
    "sfx080799+\\Slide1.wav",
    "sfx080799+\\Slide2.wav",
    " *DL* sfx080799+\\TrashCan2.wav",
    " *DL* Ambience\\BirdCall1.wav",
    " *DL* Ambience\\Cockatoo1.wav",
    " *DL* Ambience\\Cockatoo2.wav",
    " *DL* Ambience\\Cricket.wav",
    " *DL* Ambience\\FogHorn.wav",
    " *DL* Ambience\\TropicalLoop.wav",
    " *DL* GeneralMusic\\Acid.wav",
    " *DL* GeneralMusic\\Dead2MONO.wav",
    " *DL* GeneralMusic\\RoperIn.wav",
    " *DL* 6Sound.wav",
    " *DL* Ambience\\sirenAmb1.wav",
    " *DL* Ambience\\sirenAmb2.wav",
    " *DL* Ambience\\trainpass.wav",
    "RadioMessage.wav",
    " *DL* KnifeSwish.wav",
    "Stab1.wav",
    "Stab2.wav",
    "Stab3.wav",
    " *DL* BatHit1.wav",
    "BatBody1.wav",
    "Batbody2.wav",
    "DarciBatHit1.wav",
    "DarciBatHit2.wav",
    " *DL* GeneralMusic\\BriefingLoopMONO.wav",
    " *DL* GeneralMusic\\CompleteMONO.wav",
    " *DL* GeneralMusic\\FrontLoopMONO.wav",
    "DoorOpenCls1.wav",
    "Item1.wav",
    " *DL* Bat1.wav",
    " *DL* Bat2.wav",
    " *DL* Bat3.wav",
    " *DL* Bat4.wav",
    " *DL* Bat5.wav",
    " *DL* Bat6.wav",
    "Balrog\\Growl1.wav",
    "Balrog\\Growl2.wav",
    "Balrog\\Growl3.wav",
    "Balrog\\BaalStep1.wav",
    "Balrog\\BaalStep2.wav",
    "Balrog\\BalrogDeath.wav",
    "Balrog\\roar31.wav",
    "Balrog\\FlameThrown1.wav",
    "General\\Re1.wav",
    "General\\Load1.wav",
    "General\\Click2.wav",
    "General\\Clicks5.wav",
    "General\\Autorifle1.wav",
    "General\\AK1.wav",
    "General\\PickupSwish2.wav",
    "RevCarStartx.wav",
    "RevCarLoopx.wav",
    "RevCarStopx.wav",
    "General\\Bollox1.wav",
    "General\\Bollox3.wav",
    " *DL* Ambience\\Howl4.wav",
    " *DL* Ambience\\Wolves.wav",
    " *DL* Ambience\\Police1MONO.wav",
    " *DL* Ambience\\PosheataAmb1MONO.wav",
    " *DL* Ambience\\Office1MONO.wav",
    " *DL* GeneralMusic\\AlbTks\\BleepTuneMONO.wav",
    " *DL* GeneralMusic\\AlbTks\\OomaGabbaMONO.wav",
    " *DL* GeneralMusic\\AlbTks\\FeelinItMONO.wav",
    " *DL* GeneralMusic\\AlbTks\\BinaryFinaryMONO.wav",
    " *DL* GeneralMusic\\AlbTks\\TourDeForceMONO.wav",
    "JudoChop1.wav",
    "MIBexplo1.wav",
    " *DL* MIBlevitate1.wav",
    "Footsteps\\HardStep1.wav",
    "Footsteps\\HardStep2.wav",
    "Footsteps\\HardStep3.wav",
    "Footsteps\\HardStep4.wav",
    "roper\\ROPER-TAUNT03.wav",
    "roper\\ROPER-TAUNT06.wav",
    "roper\\ROPER-TAUNT04B.wav",
    "roper\\ROPER-TAUNT15.wav",
    "roper\\ROPER-TAUNT17.wav",
    "roper\\ROPER-TAUNT04.wav",
    "roper\\ROPER-TAUNT02.wav",
    "roper\\ROPER-TAUNT05.wav",
    "roper\\ROPER-TAUNT08.wav",
    "roper\\ROPER-TAUNT01.wav",
    "roper\\ROPER-TAUNT10.wav",
    "roper\\ROPER-TAUNT12.wav",
    "roper\\ROPER-TAUNT13.wav",
    "roper\\ROPER-TAUNT16.wav",
    "roper\\ROPER-TAUNT16B.wav",
    "roper\\ROPER-TAUNT19.wav",
    "roper\\ROPER-TAUNT18.wav",
    "roper\\ROPER-TAUNT20.wav",
    "roper\\ROPER-TAUNT09.wav",
    "roper\\ROPER-TAUNT18B.wav",
    "darci\\DARCI-TAUNT09.wav",
    "darci\\DARCI-TAUNT19C.wav",
    "darci\\DARCI-TAUNT19D.wav",
    "darci\\DARCI-TAUNT02B.wav",
    "darci\\DARCI-TAUNT13.wav",
    "darci\\DARCI-TAUNT13B.wav",
    "darci\\DARCI-TAUNT09B.wav",
    "darci\\DARCI-TAUNT01B.wav",
    "darci\\DARCI-TAUNT03.wav",
    "darci\\DARCI-TAUNT06GB.wav",
    "darci\\DARCI-TAUNT07.wav",
    "darci\\DARCI-TAUNT08.wav",
    "darci\\DARCI-TAUNT08B.wav",
    "darci\\DARCI-TAUNT10.wav",
    "darci\\DARCI-TAUNT10B.wav",
    "darci\\DARCI-TAUNT01.wav",
    "darci\\DARCI-TAUNT18.wav",
    "darci\\DARCI-TAUNT18B.wav",
    "darci\\DARCI-TAUNT19.wav",
    "darci\\DARCI-TAUNT19B.wav",
    "darci\\DARCI-TAUNT16.wav",
    "darci\\DARCI-TAUNT04.wav",
    "darci\\DARCI-TAUNT04B.wav",
    "darci\\DARCI-TAUNT16B.wav",
    "darci\\DARCI-TAUNT12.wav",
    "darci\\DARCI-TAUNT17.wav",
    "darci\\DARCI-TAUNT14.wav",
    "darci\\DARCI-TAUNT15B.wav",
    "darci\\DARCI-TAUNT15.wav",
    "darci\\DARCI-TAUNT12B.wav",
    "darci\\DARCI-ARREST02B.wav",
    "darci\\DARCI-ARREST01B.wav",
    "darci\\DARCI-ARREST02.wav",
    "darci\\DARCI-ARREST01.wav",
    "bthug1\\GRASTA-TAUNT07.wav",
    "bthug1\\GRASTA-TAUNT02.wav",
    "bthug1\\GRASTA-TAUNT02B.wav",
    "bthug1\\GRASTA-TAUNT03.wav",
    "bthug1\\GRASTA-TAUNT04.wav",
    "bthug1\\GRASTA-TAUNT04B.wav",
    "bthug1\\GRASTA-TAUNT05.wav",
    "bthug1\\GRASTA-TAUNT06.wav",
    "bthug1\\GRASTA-TAUNT01.wav",
    "wthug1\\GGREY-TAUNT05B.wav",
    "wthug1\\GGREY-TAUNT01B.wav",
    "wthug1\\GGREY-TAUNT02.wav",
    "wthug1\\GGREY-TAUNT02B.wav",
    "wthug1\\GGREY-TAUNT03.wav",
    "wthug1\\GGREY-TAUNT03B.wav",
    "wthug1\\GGREY-TAUNT04.wav",
    "wthug1\\GGREY-TAUNT04B.wav",
    "wthug1\\GGREY-TAUNT05.wav",
    "wthug1\\GGREY-TAUNT01.wav",
    "wthug2\\GRED-TAUNT05B.wav",
    "wthug2\\GRED-TAUNT01B.wav",
    "wthug2\\GRED-TAUNT02B.wav",
    "wthug2\\GRED-TAUNT03B.wav",
    "wthug2\\GRED-TAUNT04B.wav",
    "wthug2\\GRED-TAUNT01.wav",
    "wthug2\\GRED-TAUNT02.wav",
    "wthug2\\GRED-TAUNT03.wav",
    "wthug2\\GRED-TAUNT04.wav",
    "wthug2\\GRED-TAUNT05.wav",
    "cop\\COP-ARREST01.wav",
    "cop\\COP-ARREST02.wav",
    "cop\\COP-ARREST03.wav",
    "cop\\COP-ARREST04.wav",
    "cop\\COP-DIE01.wav",
    "cop\\COP-DIE02B.wav",
    "cop\\COP-DIE03.wav",
    "cop\\COP-DIE04.wav",
    "cop\\COP-DIE04B.wav",
    "cop\\COP-PAIN01.wav",
    "cop\\COP-PAIN02.wav",
    "cop\\COP-PAIN03.wav",
    "cop\\COP-PAIN03B.wav",
    "cop\\COP-PAIN04.wav",
    "cop\\COP-TAUNT08.wav",
    "cop\\COP-TAUNT02.wav",
    "cop\\COP-TAUNT03.wav",
    "cop\\COP-TAUNT04.wav",
    "cop\\COP-TAUNT05.wav",
    "cop\\COP-TAUNT06.wav",
    "cop\\COP-TAUNT07.wav",
    "cop\\COP-TAUNT01.wav",
    "Reckoning1.wav",
    " *DL* GeneralMusic\\Bonus.wav",
    "MIBgun1.wav",
    "MIBgun1wd.wav",
    "Footsteps\\SoftStep1.wav",
    "Footsteps\\SoftStep2.wav",
    "Footsteps\\SoftStep3.wav",
    "Footsteps\\SoftStep4.wav",
    "MIBwarning1.wav",
    "Paintgun1.wav",
    "ScreamF1.wav",
    "ScreamF2.wav",
    "ScreamM1.wav",
    " *DL* GeneralMusic\\CreditDue.wav",
    "ExploFireball2.wav",
    "ExploFireball3.wav",
    "misc\\GRASTA-PAIN02.wav",
    "misc\\GRASTA-PAIN02B.wav",
    "misc\\GRASTA-PAIN01.wav",
    "misc\\GRASTA-PAIN05.wav",
    "misc\\GRED-PAIN01.wav",
    "misc\\GRED-PAIN01B.wav",
    "misc\\GRED-PAIN02.wav",
    "misc\\GRED-PAIN02B.wav",
    "misc\\HOSTAGE-PAIN01.wav",
    "misc\\HOSTAGE-PAIN01B.wav",
    "misc\\HOSTAGE-PAIN02.wav",
    "misc\\HOSTAGE-PAIN02B.wav",
    "misc\\GWORK-PAIN01.wav",
    "misc\\GWORK-PAIN03.wav",
    "misc\\GWORK-PAIN04.wav",
    "misc\\GWORK-PAIN05.wav",
    "misc\\GGREY-PAIN02.wav",
    "misc\\GGREY-PAIN02B.wav",
    "misc\\GGREY-PAIN05.wav",
    "misc\\GTRAMP-PAIN01.wav",
    "misc\\GTRAMP-PAIN02.wav",
    "misc\\GTRAMP-PAIN03.wav",
    "misc\\GTRAMP-PAIN04.wav",
    "misc\\GTRAMP-PAIN05.wav",
    " *DL* GeneralMusic\\AlbTks\\ADFoundationMONO.wav",
	"GeneralMusic\\FrontLoopEditMONO.wav",
    "!",
    };

#endif

